#messages - some support %player%, but every support color codes (&a, &1, etc)
messages:
  #appears when someone clears the chat
  chat-cleared-global: "The chat has been cleared by %player_name%"
  #appears when someone locks the chat while it is already locked
  #appears when someone locks the chat
  chat-lock-success-all: "Chat locked by %player_name%!"
  #appears when someone unlocks the chat
  chat-unlock-success-all: "Chat unlocked by %player_name%!"
  #appears when someone sends a message during chat-lock
  message-during-lock: "You cannot send this message because the chat is locked!"
  #appears when a message someone sent contains a badword from the "badwords" list below
  contains-badword: "This message contains a bad word set up by the administrator and you cannot send this!"
  #appears when someone sends a message while they are on cooldown
  chat-cooldown-reached: "Please wait %seconds% seconds before typing the next message!"
  #appears when someone uses a command that he doesnt have permissions to
  noperms: "You don't have enough permissions!"
  #appears when someone uses /sudo with wrong arguments
  sudo-less-args: "There are not enough arguments! Use /sudo <player> <message/command>"
  #appears when someone tries to use /sudo on an offline player
  sudo-player-offline: "This player is offline"
  #if antylink-cancel-send-if-link-detected is true and someone sends a link, this will appear to them
  contains-link: "This message contains a link and has not been sent"
  #appears when someone uses /broadcast with wrong arguments
  broadcast-less-args: "Wrong amount of arguments! use /broadcast <message>"
  #appears when someone uses /staffchat with wrong arguments
  staffchat-less-args: "Wrong amount of arguments! use /staffchat <message>"


#broadcast settings
#the way how broadcasting will look like (use %broadcast_msg% to get the broadcast message)
broadcast-format: "&b&lMy&e&lServer&f&l.EU &8| &7%broadcast_msg%"

#chat cooldown in milliseconds
chat-cooldown: 3000


#antylink is beta
#antylink options (PLEASE CHOOSE ONLY ONE OPTION, OTHERWISE IT MAY MEET ERRORS)
#remove dots from the player's message in the link
antylink-remove-dots: false
#remove the player's message if it contains a link, and send him the "contains-link" message from config
antylink-cancel-send-if-link-detected: false

#staff chat settings
#format:
staff-chat-format: "&d[&bSTAFF&d] %player_name% &c%message%"
#permission to receive and send messages:
staff-chat-permission: "cplusreloaded.staffchat"


#Chat formatting
#Built-in placeholders: %player%, %messages%
#You can use PlaceHolderAPI and Vault to get ranks/prefixes, etc.
enable-chat-formatting: false
chat-format: "<%player_name%> %message%"

#list of words that are not allowed
badwords:
  - 'anus'
  - 'arsch'
  - 'arschloch'
  - 'arse'
  - 'arsehole'
  - 'ass'
  - 'assbag'
  - 'assbandit'
  - 'assbanger'
  - 'assbite'
  - 'assclown'
  - 'asscock'
  - 'asscracker'
  - 'asses'
  - 'assface'
  - 'assfuck'
  - 'assfucker'
  - 'assgoblin'
  - 'asshat'
  - 'asshead'
  - 'asshole'
  - 'asshopper'
  - 'assjabber'
  - 'assjacker'
  - 'asslick'
  - 'asslicker'
  - 'assmonkey'
  - 'assmunch'
  - 'assmuncher'
  - 'assnigger'
  - 'asspirate'
  - 'assshit'
  - 'asssucker'
  - 'asswad'
  - 'asswipe'
  - 'axwound'
  - 'bampot'
  - 'bastard'
  - 'batard'
  - 'beaner'
  - 'biatch'
  - 'bitch'
  - 'bitchass'
  - 'bitches'
  - 'bitchtits'
  - 'bitchy'
  - 'bite'
  - 'bitte'
  - 'blowjob'
  - 'blödmann'
  - 'bollocks'
  - 'bollox'
  - 'boner'
  - 'bouffon'
  - 'bougnoul'
  - 'branler'
  - 'branleur'
  - 'brotherfucker'
  - 'bullshit'
  - 'bumblefuck'
  - 'buttfucka'
  - 'buttfucker'
  - 'buttpirate'
  - 'buttplug'
  - 'bâtard'
  - 'cameltoe'
  - 'carpetmuncher'
  - 'chesticle'
  - 'chiennasse'
  - 'chienne'
  - 'childfucker'
  - 'chinc'
  - 'chink'
  - 'choad'
  - 'chode'
  - 'clit'
  - 'clitface'
  - 'clitfuck'
  - 'clusterfuck'
  - 'cock'
  - 'cockass'
  - 'cockbite'
  - 'cockburger'
  - 'cockface'
  - 'cockfucker'
  - 'cockhead'
  - 'cockjockey'
  - 'cockknoker'
  - 'cockmaster'
  - 'cockmongler'
  - 'cockmongruel'
  - 'cockmonkey'
  - 'cockmuncher'
  - 'cocknose'
  - 'cocknugget'
  - 'cockshit'
  - 'cocksmith'
  - 'cocksmoke'
  - 'cocksmoker'
  - 'cocksniffer'
  - 'cocksucker'
  - 'cockwaffle'
  - 'connard'
  - 'connasse'
  - 'coochie'
  - 'coochy'
  - 'coon'
  - 'cooter'
  - 'couille'
  - 'cracker'
  - 'cum'
  - 'cumbubble'
  - 'cumdumpster'
  - 'cumguzzler'
  - 'cumjockey'
  - 'cumslut'
  - 'cumtart'
  - 'cunnie'
  - 'cunnilingus'
  - 'cunt'
  - 'cuntass'
  - 'cuntface'
  - 'cunthole'
  - 'cuntlicker'
  - 'cuntrag'
  - 'cuntslut'
  - 'dago'
  - 'damn'
  - 'deggo'
  - 'demelda'
  - 'dick'
  - 'dickbag'
  - 'dickbeaters'
  - 'dickface'
  - 'dickfuck'
  - 'dickfucker'
  - 'dickhead'
  - 'dickhole'
  - 'dickjuice'
  - 'dickmilk'
  - 'dickmonger'
  - 'dickslap'
  - 'dicksucker'
  - 'dicksucking'
  - 'dicktickler'
  - 'dickwad'
  - 'dickweasel'
  - 'dickweed'
  - 'dickwod'
  - 'dike'
  - 'dildo'
  - 'dipshit'
  - 'doochbag'
  - 'dooche'
  - 'dookie'
  - 'douche'
  - 'douchebag'
  - 'douchefag'
  - 'douchewaffle'
  - 'dumass'
  - 'dumbass'
  - 'dumbfuck'
  - 'dumbshit'
  - 'dumshit'
  - 'dyke'
  - 'encule'
  - 'enculé'
  - 'fag'
  - 'fagbag'
  - 'fagfucker'
  - 'faggit'
  - 'faggot'
  - 'faggotcock'
  - 'fagtard'
  - 'fatass'
  - 'fdp'
  - 'fellatio'
  - 'feltch'
  - 'flamer'
  - 'foutre'
  - 'fu'
  - 'fuck'
  - 'fuckass'
  - 'fuckbag'
  - 'fuckboy'
  - 'fuckbrain'
  - 'fuckbutt'
  - 'fuckbutter'
  - 'fucked'
  - 'fucker'
  - 'fuckersucker'
  - 'fuckface'
  - 'fuckhead'
  - 'fuckhole'
  - 'fuckin'
  - 'fucking'
  - 'fucknut'
  - 'fucknutt'
  - 'fuckoff'
  - 'fucks'
  - 'fuckstick'
  - 'fucktard'
  - 'fucktart'
  - 'fucku'
  - 'fuckup'
  - 'fuckwad'
  - 'fuckwit'
  - 'fuckwitt'
  - 'fuckyou'
  - 'fudgepacker'
  - 'furzen'
  - 'fyou'
  - 'garce'
  - 'gay'
  - 'gayass'
  - 'gaybob'
  - 'gaydo'
  - 'gayfuck'
  - 'gayfuckist'
  - 'gaylord'
  - 'gaytard'
  - 'gaywad'
  - 'gland'
  - 'goddamn'
  - 'goddamnit'
  - 'gooch'
  - 'gook'
  - 'gringo'
  - 'guido'
  - 'handjob'
  - 'hardon'
  - 'heeb'
  - 'ho'
  - 'hoe'
  - 'hollyfuck'
  - 'hollyfuckingshit'
  - 'hollyshit'
  - 'homo'
  - 'homodumbshit'
  - 'homoshit'
  - 'honkey'
  - 'humping'
  - 'hölle'
  - 'imbécile'
  - 'ip'
  - 'jackass'
  - 'jagoff'
  - 'jap'
  - 'jerkass'
  - 'jerkoff'
  - 'jesus'
  - 'jesuschrist'
  - 'jesusharoldchrist'
  - 'jesushchrist'
  - 'jesusmaryjoseph'
  - 'jesuswept'
  - 'jigaboo'
  - 'jizz'
  - 'judaspriest'
  - 'junglebunny'
  - 'kacken'
  - 'kike'
  - 'kooch'
  - 'kootch'
  - 'kotzen'
  - 'kraut'
  - 'kunt'
  - 'kyke'
  - 'lameass'
  - 'lardass'
  - 'lesbian'
  - 'lesbo'
  - 'lezzie'
  - 'mcfagget'
  - 'merde'
  - 'merdeu'
  - 'mick'
  - 'mierda'
  - 'minge'
  - 'mongol'
  - 'mothafucka'
  - 'mothafucking'
  - 'motherfucka'
  - 'motherfucker'
  - 'muff'
  - 'muffdiver'
  - 'munging'
  - 'negro'
  - 'nigaboo'
  - 'nigga'
  - 'nigger'
  - 'niglet'
  - 'nique'
  - 'ntm'
  - 'nutsack'
  - 'négro'
  - 'paki'
  - 'panooch'
  - 'pecker'
  - 'peckerhead'
  - 'pede'
  - 'penis'
  - 'penisbanger'
  - 'penisfucker'
  - 'penispuffer'
  - 'piss'
  - 'pissed'
  - 'pissflaps'
  - 'polesmoker'
  - 'pollock'
  - 'poon'
  - 'poonani'
  - 'poonany'
  - 'poontang'
  - 'porchmonkey'
  - 'prick'
  - 'punanny'
  - 'punta'
  - 'pupsen'
  - 'pussies'
  - 'pussy'
  - 'pussylicking'
  - 'puta'
  - 'putain'
  - 'pute'
  - 'puto'
  - 'pédé'
  - 'queef'
  - 'queer'
  - 'queerbait'
  - 'queerhole'
  - 'renob'
  - 'rimjob'
  - 'ruski'
  - 'sandnigger'
  - 'scheisse'
  - 'scheissen'
  - 'schlong'
  - 'scrote'
  - 'sex'
  - 'shit'
  - 'shitass'
  - 'shitbag'
  - 'shitbagger'
  - 'shitbrains'
  - 'shitbreath'
  - 'shitcanned'
  - 'shitcunt'
  - 'shitdick'
  - 'shitface'
  - 'shitfaced'
  - 'shithead'
  - 'shithole'
  - 'shithouse'
  - 'shitspitter'
  - 'shitstain'
  - 'shitter'
  - 'shittiest'
  - 'shitting'
  - 'shitty'
  - 'shiz'
  - 'shiznit'
  - 'skank'
  - 'skeet'
  - 'skullfuck'
  - 'slut'
  - 'slutbag'
  - 'smeg'
  - 'snatch'
  - 'sonofabitch'
  - 'sonofamotherlessgoat'
  - 'sonofawhore'
  - 'spic'
  - 'spick'
  - 'splooge'
  - 'spook'
  - 'suckass'
  - 'sweetjesus'
  - 'tard'
  - 'testicle'
  - 'thundercunt'
  - 'tit'
  - 'tits'
  - 'titfuck'
  - 'tittyfuck'
  - 'twat'
  - 'twatlips'
  - 'twatwaffle'
  - 'unclefucker'
  - 'vag'
  - 'vagina'
  - 'vajayjay'
  - 'vajj'
  - 'vjayjay'
  - 'vjj'
  - 'wank'
  - 'wankjob'
  - 'wetback'
  - 'whore'
  - 'whorebag'
  - 'whoreface'
  - 'wop'
  - 'cuck'